version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Test
          command: |
            pip install pytest
            pytest
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
            py.test --cov=tests --cov=core --cov-report xml
            ./cc-test-reporter after-build --coverage-input-type coverage.py --exit-code $?
        
workflows:
  main:
    jobs:
      - build-and-test
