version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    environment:
      CC_TEST_REPORTER_ID: cdfdef2e505117577cfd3a5771853df55e157b48fb5f2cb6d1d19c60d27fc55f

    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Test
          command: |
            ./cc-test-reporter before-build
            py.test --cov=tests --cov=core --cov-report xml
            ./cc-test-reporter after-build --coverage-input-type coverage.py --exit-code $?
        
workflows:
  main:
    jobs:
      - build-and-test
